### PR TITLE
Don't assume the getData returns a dict

### LINKED ISSUE #109: Problem when using both model and template form
I have a tabulator that uses a model object and also an anvil form for the row. Under some circumstances, I get an error:
```
TypeError: MyModel object is not iterable
at app/tabulator/Tabulator/_custom_modules.py:61
called from app/tabulator/Tabulator/_custom_modules.py:
called from app/tabulator/Tabulator/_helpers.py:144
```
Looking at the `_custom_modules` code, I can see that it passes the model object to the `dict` function and therefore expects it to implement the mapping protocol.

So, I can fix the error by implementing `keys` and `__getitem__` in my model, but it feels like I shouldn't have to.

I haven't quite nailed what exactly the circumstances are that raise the error, so I can't put an MWE together - the app I'm using stores data in local storage and uses hash routing. When I add a new item, the app routes to a 'creation' form, adds the new item to local storage, routes back and refreshes the tabulator data. Somewhere in there, it sometimes goes wrong, but not always!

### PR DESCRIPTION
**Pull request by s-cork**
close #109

@meatballs - let me know if this fixes the issue and I'll put it onto the production branch

### CODE REVIEW

**Comment by meatballs** [comment]
Now I get a slightly different issue...

In the row template form, I now can't use a data binding.

Sometimes, the template gets the model and complains if I use indexing for the binding (unless I reinstate `__getitem__`).
Other times, it gets a dict and complains if I use an attribute.

**Comment by meatballs** [comment]
Again, I'm not quite sure of the circumstances when the template gets the model instance or the dict - but it seems to be the dict when the tabulator first loads but the model instance when I return from creating a new value.

**Comment by s-cork** [comment]
@meatballs 
try now sorry - might have fixed it - might not

**Comment by meatballs** [comment]
Still the same problem with the binding. I'll try to carve out some time for an MWE

**Comment by s-cork** [comment]
Ta - think an MWE is gonna be necessary here

**Comment by meatballs** [comment]
All sorted. Dumb stupid user error, this one!

**Pull request merged**
