### PR TITLE
Data loading

### LINKED ISSUE #28: Loading App Tables in options issue
Hey I am trying to leverage the native function to pass an app table as the data to the Tabulator but I keep getting no rows to display.

Here is a clone link: https://anvil.works/build#clone:OYM2GBKFNX5XXE3R=YWZGVWTUR43NVMA5P2H53QPE|TGQCF3WT6FVL2EM2=

I define my tabulator under the init as 
```
    self.tabulator_1.columns = [
      {"title": "Name", "field": "name"},
      {"title": "Status", "field": "status"},
      {"title": "Error", "field": "error"},
    ]
    self.tabulator_1.options = {
      "app_table": anvil.server.call('get_data'),
      "data_loader": False, # display JS Tabulators 'loading' component
      "loading_indicator": False # defaults to True - whether to use the anvil spinner during page loading
    }
```
And my server call as 
```
@anvil.server.callable
def get_data():
  return app_tables.table_1.client_readable()
```
And the result:

image

### PR DESCRIPTION
**Pull request by s-cork**
@expressintegrations - I think i've addressed #28  in this PR

I'm gonna merge to master - so you can try it out on the development branch.

I'll hold off bumping the version number until you've had a chance to look at it.

close #28

### CODE REVIEW

**Comment by expressintegrations** [comment]
YES! This is great. Much simpler on the end user now without needing to explicitly set an index for an app table and the row selection works like a charm. Thanks so much!

**Comment by s-cork** [comment]
great that's now at `v2.1.2` if you want to pin to a version number rather than the Development branch

**Comment by expressintegrations** [comment]
Is it possible to use a custom filter of app table data? So far I have only been able to use the `set_query` method, and `set_filter` doesn't work at all.

**Comment by s-cork** [comment]
Can you give an example of set filter that couldn't be handled by set query?

Since We're using app tables any filter would need to be converted to a query to actually make it search the table.

The native set filter won't work out of the box because the search is lazy and so tabulator doesn't necessarily have all the data to actually do a filter. 

I didn't implement that since it was a bit of a headache to think about how to use js tabulator semantics in anvils query api.

**Comment by expressintegrations** [comment]
The example I was working on was that I was using a dropdown and a text box to filter the data in the table. I only wanted to filter the data if the user enters a value in the text box or selects a value, and the filter should apply the values from both inputs. I was using the custom filter method to check if the filtering components had a value as well as to check if the data matched the value. Here is an example: https://anvil.works/build#clone:OYM2GBKFNX5XXE3R=YWZGVWTUR43NVMA5P2H53QPE|TGQCF3WT6FVL2EM2=

**Comment by expressintegrations** [comment]
Set query can't handle checking if the value of the component is None or the text box is empty, because it expects to check the value of the columns in the table only.

**Comment by s-cork** [comment]
That type of function filter just won't work with an app_table. 

Part of the draw of the app_table option is to be lazy with fetching data. And so if I can't pass it as an argument to app_tables.my_table.search() then the tabulator app_tables option can't handle it. 

But that function can easily be turned into an anvil query. Using a combination of q.all_of, q.ilike and such. 


Pseudo code

```python 
query = {}
if selected_text:
  query["name"] = selected_name
elif text:
   query["name"] = q.like(f"%{text}%")

if selected_status:
   query["status"] = selected_status

self.tabulator.set_query(**query)
```

**Comment by expressintegrations** [comment]
aha ok I will go that route. Thanks!

**Pull request merged**
